export const hexagrams = [
  { number: 1, name: "The Creative", symbol: "䷀", description: "The Creative represents the primal power of creation and the power of spirit." },
  { number: 2, name: "The Receptive", symbol: "䷁", description: "The Receptive represents the power of yielding and acceptance." },
  { number: 3, name: "Difficulty at the Beginning", symbol: "䷂", description: "Difficulty at the Beginning represents the challenges of new undertakings." },
  { number: 4, name: "Youthful Folly", symbol: "䷃", description: "Youthful Folly represents inexperience and the need for guidance." },
  { number: 5, name: "Waiting", symbol: "䷄", description: "Waiting represents patience and the right timing for action." },
  { number: 6, name: "Conflict", symbol: "䷅", description: "Conflict represents discord and the need for resolution." },
  { number: 7, name: "The Army", symbol: "䷆", description: "The Army represents discipline and organized action." },
  { number: 8, name: "Holding Together", symbol: "䷇", description: "Holding Together represents unity and cooperation." },
  { number: 9, name: "Small Taming", symbol: "䷈", description: "Small Taming represents gentle restraint and gradual progress." },
  { number: 10, name: "Treading", symbol: "䷉", description: "Treading represents careful conduct in difficult situations." },
  { number: 11, name: "Peace", symbol: "䷊", description: "Peace represents harmony and prosperity." },
  { number: 12, name: "Standstill", symbol: "䷋", description: "Standstill represents stagnation and the need for change." },
  { number: 13, name: "Fellowship", symbol: "䷌", description: "Fellowship represents community and shared purpose." },
  { number: 14, name: "Great Possession", symbol: "䷍", description: "Great Possession represents abundance and responsibility." },
  { number: 15, name: "Modesty", symbol: "䷎", description: "Modesty represents humility and inner strength." },
  { number: 16, name: "Enthusiasm", symbol: "䷏", description: "Enthusiasm represents motivation and inspiration." },
  { number: 17, name: "Following", symbol: "䷐", description: "Following represents adaptation and alignment with natural forces." },
  { number: 18, name: "Work on the Decayed", symbol: "䷑", description: "Work on the Decayed represents renewal and addressing corruption." },
  { number: 19, name: "Approach", symbol: "䷒", description: "Approach represents steady advancement and opportunity." },
  { number: 20, name: "Contemplation", symbol: "䷓", description: "Contemplation represents observation and reflection." },
  { number: 21, name: "Biting Through", symbol: "䷔", description: "Biting Through represents overcoming obstacles through persistence." },
  { number: 22, name: "Grace", symbol: "䷕", description: "Grace represents beauty and form in social interactions." },
  { number: 23, name: "Splitting Apart", symbol: "䷖", description: "Splitting Apart represents disintegration and the need for caution." },
  { number: 24, name: "Return", symbol: "䷗", description: "Return represents cyclical change and renewal." },
  { number: 25, name: "Innocence", symbol: "䷘", description: "Innocence represents natural behavior and spontaneity." },
  { number: 26, name: "Great Taming", symbol: "䷙", description: "Great Taming represents accumulation of energy and self-control." },
  { number: 27, name: "Mouth Corners", symbol: "䷚", description: "Mouth Corners represents nourishment and care for oneself and others." },
  { number: 28, name: "Great Preponderance", symbol: "䷛", description: "Great Preponderance represents critical mass and the need for balance." },
  { number: 29, name: "The Abysmal Water", symbol: "䷜", description: "The Abysmal Water represents danger and the opportunity for growth." },
  { number: 30, name: "The Clinging Fire", symbol: "䷝", description: "The Clinging Fire represents clarity and attachment." },
  { number: 31, name: "Influence", symbol: "䷞", description: "Influence represents attraction and mutual stimulation." },
  { number: 32, name: "Duration", symbol: "䷟", description: "Duration represents perseverance and continuity." },
  { number: 33, name: "Retreat", symbol: "䷠", description: "Retreat represents strategic withdrawal and conservation of energy." },
  { number: 34, name: "Great Power", symbol: "䷡", description: "Great Power represents controlled strength and vigor." },
  { number: 35, name: "Progress", symbol: "䷢", description: "Progress represents gradual advancement and expansion." },
  { number: 36, name: "Darkening of the Light", symbol: "䷣", description: "Darkening of the Light represents adversity and the need for perseverance." },
  { number: 37, name: "The Family", symbol: "䷤", description: "The Family represents social order and harmonious relationships." },
  { number: 38, name: "Opposition", symbol: "䷥", description: "Opposition represents contrast and complementary forces." },
  { number: 39, name: "Obstruction", symbol: "䷦", description: "Obstruction represents difficulties and the need for reflection." },
  { number: 40, name: "Deliverance", symbol: "䷧", description: "Deliverance represents release from tension and resolution." },
  { number: 41, name: "Decrease", symbol: "䷨", description: "Decrease represents reduction and simplification." },
  { number: 42, name: "Increase", symbol: "䷩", description: "Increase represents gain and expansion." },
  { number: 43, name: "Breakthrough", symbol: "䷪", description: "Breakthrough represents resoluteness and overcoming resistance." },
  { number: 44, name: "Coming to Meet", symbol: "䷫", description: "Coming to Meet represents encountering and handling temptation." },
  { number: 45, name: "Gathering Together", symbol: "䷬", description: "Gathering Together represents unity and collective action." },
  { number: 46, name: "Pushing Upward", symbol: "䷭", description: "Pushing Upward represents gradual progress and ascending." },
  { number: 47, name: "Oppression", symbol: "䷮", description: "Oppression represents exhaustion and the need for perseverance." },
  { number: 48, name: "The Well", symbol: "䷯", description: "The Well represents replenishment and access to resources." },
  { number: 49, name: "Revolution", symbol: "䷰", description: "Revolution represents fundamental change and renewal." },
  { number: 50, name: "The Cauldron", symbol: "䷱", description: "The Cauldron represents transformation and refinement." },
  { number: 51, name: "The Arousing Thunder", symbol: "䷲", description: "The Arousing Thunder represents sudden change and awakening." },
  { number: 52, name: "The Keeping Still Mountain", symbol: "䷳", description: "The Keeping Still Mountain represents meditation and stillness." },
  { number: 53, name: "Development", symbol: "䷴", description: "Development represents gradual progress and growth." },
  { number: 54, name: "The Marrying Maiden", symbol: "䷵", description: "The Marrying Maiden represents subordinate relationships and inequality." },
  { number: 55, name: "Abundance", symbol: "䷶", description: "Abundance represents fullness and peak of success." },
  { number: 56, name: "The Wanderer", symbol: "䷷", description: "The Wanderer represents transience and adaptability." },
  { number: 57, name: "The Gentle Wind", symbol: "䷸", description: "The Gentle Wind represents subtle influence and penetration." },
  { number: 58, name: "The Joyous Lake", symbol: "䷹", description: "The Joyous Lake represents pleasure and satisfaction." },
  { number: 59, name: "Dispersion", symbol: "䷺", description: "Dispersion represents dissolution and overcoming egotism." },
  { number: 60, name: "Limitation", symbol: "䷻", description: "Limitation represents boundaries and the need for moderation." },
  { number: 61, name: "Inner Truth", symbol: "䷼", description: "Inner Truth represents sincerity and centering." },
  { number: 62, name: "Small Preponderance", symbol: "䷽", description: "Small Preponderance represents attention to detail and caution." },
  { number: 63, name: "After Completion", symbol: "䷾", description: "After Completion represents transition and maintaining balance." },
  { number: 64, name: "Before Completion", symbol: "䷿", description: "Before Completion represents approaching the end and preparing for a new beginning." }
];

